#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""topoSetDict + createBafflesDict for brand_topology lane separators.

For each pair (Lane n, Lane n+1) the dividing wall consists of:
    - the faces shared between Bend_Lane{n} and Bend_Lane{n+1}
    - the faces shared between Trail_Lane{n} and Trail_Lane{n+1}  (if L_trail > 0)

Feed and Run portions of the lane interfaces stay INTERNAL (no baffle there).
This matches the physical idea of a guide vane: a finite-length insert in the
bend (and optionally a Trail extension), not a full-channel partition.

cellZone-based identification (same scheme as A2-mother's gen_createbaffles.py):
    1. Build cellSet v{i}lo from Bend_Lane{i} (+ Trail_Lane{i} if has_trail)
    2. Build cellSet v{i}hi from Bend_Lane{i+1} (+ Trail_Lane{i+1})
    3. faceSet vane{i}Faces = cellToFace(v{i}lo)
    4. Subset: vane{i}Faces ∩= cellToFace(v{i}hi)  -> only shared faces
    5. setsToFaceZone -> vane{i}FaceZone (oriented via v{i}hi)
    6. createBafflesDict: each faceZone -> wall patches vane{i}_master + vane{i}_slave
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

from gen_blockmesh import BrandTopology, build_topology, _from_params_json


_HEADER_TOPO = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
|  \\\\      /  F ield        | OpenFOAM                                        |
|   \\\\    /   O peration    | CFDPredict A2 -- brand_topology                |
|    \\\\  /    A nd          | generated by gen_createbaffles.py              |
|     \\\\/     M anipulation |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      topoSetDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


_HEADER_BAFFLES = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
|  \\\\      /  F ield        | OpenFOAM                                        |
|   \\\\    /   O peration    | CFDPredict A2 -- brand_topology                |
|    \\\\  /    A nd          | generated by gen_createbaffles.py              |
|     \\\\/     M anipulation |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      createBafflesDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def n_vanes(geo: BrandTopology) -> int:
    """Number of internal lane-separator vanes = len(inner_arc_fractions)."""
    return len(geo.inner_arc_fractions)


def render_toposet(geo: BrandTopology) -> str:
    n_v = n_vanes(geo)
    if n_v == 0:
        raise ValueError("no vanes -- inner_arc_fractions is empty")
    has_trail = geo.L_trail > 0.0

    lines = [_HEADER_TOPO, "", "actions", "("]

    for v in range(1, n_v + 1):
        # Vane v separates Lane v (lo) from Lane v+1 (hi).
        lo_zones = [f"Bend_Lane{v}"]
        hi_zones = [f"Bend_Lane{v + 1}"]
        if has_trail:
            lo_zones.append(f"Trail_Lane{v}")
            hi_zones.append(f"Trail_Lane{v + 1}")
        lo_str = "( " + " ".join(lo_zones) + " )"
        hi_str = "( " + " ".join(hi_zones) + " )"

        lines += [
            "    {",
            f"        name    v{v}lo;",
            "        type    cellSet;",
            "        action  new;",
            "        source  zoneToCell;",
            f"        zones   {lo_str};",
            "    }",
            "    {",
            f"        name    v{v}hi;",
            "        type    cellSet;",
            "        action  new;",
            "        source  zoneToCell;",
            f"        zones   {hi_str};",
            "    }",
            "    {",
            f"        name    vane{v}Faces;",
            "        type    faceSet;",
            "        action  new;",
            "        source  cellToFace;",
            f"        sets    (v{v}lo);",
            "        option  all;",
            "    }",
            "    {",
            f"        name    vane{v}Faces;",
            "        type    faceSet;",
            "        action  subset;",
            "        source  cellToFace;",
            f"        sets    (v{v}hi);",
            "        option  all;",
            "    }",
            "    {",
            f"        name    vane{v}FaceZone;",
            "        type    faceZoneSet;",
            "        action  new;",
            "        source  setsToFaceZone;",
            f"        faceSet vane{v}Faces;",
            f"        cellSet v{v}hi;",
            "    }",
        ]
    lines += [");", ""]
    return "\n".join(lines)


def render_createbaffles(geo: BrandTopology) -> str:
    n_v = n_vanes(geo)
    if n_v == 0:
        raise ValueError("no vanes -- inner_arc_fractions is empty")

    lines = [
        _HEADER_BAFFLES, "",
        "internalFacesOnly true;",
        "fields            false;",
        "",
        "baffles",
        "{",
    ]
    for v in range(1, n_v + 1):
        lines += [
            f"    vane{v}",
            "    {",
            "        type            faceZone;",
            f"        zoneName        vane{v}FaceZone;",
            "        patches",
            "        {",
            f"            master {{ name vane{v}_master; type wall; }}",
            f"            slave  {{ name vane{v}_slave;  type wall; }}",
            "        }",
            "    }",
        ]
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--params", default="params.json")
    ap.add_argument("--target-dir", type=Path, default=Path("system"),
                    help="Where to write topoSetDict + createBafflesDict")
    args = ap.parse_args()

    geo = _from_params_json(args.params)
    args.target_dir.mkdir(parents=True, exist_ok=True)
    (args.target_dir / "topoSetDict").write_text(
        render_toposet(geo), encoding="utf-8", newline="\n")
    (args.target_dir / "createBafflesDict").write_text(
        render_createbaffles(geo), encoding="utf-8", newline="\n")
    print(f"wrote topoSetDict + createBafflesDict to {args.target_dir}/  "
          f"({n_vanes(geo)} vane(s); has_trail={geo.L_trail > 0.0})")


if __name__ == "__main__":
    main()
