#!/usr/bin/env python3
"""Generate the 16 Zhang L16(4^4)-DOE-Case-Configs as interface.json-Files.

Zhang 2023 Sektion 4.3 Taguchi-Design — vier Faktoren mit je 4 Levels (Tabelle 3
im Paper). 16 Cases statt 256 (Voll-Faktorial) via Standard-Taguchi-L16-Array.
Pro Case wird der DOE-Code (`A_iB_jC_kD_l`) in das Form-Feld geschrieben; der
Worker decodet via `parse_doe_code()` -> Geometrie ueberschreibt Defaults.

Output: 16 JSONs `A1B1C1D1.json` ... `A4B4C4D3.json` (in diesem Ordner), plus
ein `README.md` mit Hinweisen zur Benutzung (manuell via Portal vs Batch via
`tools/run_workflow.py`).
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMA = HERE.parent.parent / "workflows" / "A3_nozzle" / "interface.json"

# Zhang L16(4^4) Taguchi-Array (Standardanordnung, 4 Faktoren x 4 Levels = 16 Rows)
# Zeilen sind (A, B, C, D) = (beta, Do, alpha, Ds)-Levels (jeweils 1..4).
# Genau diese Spaltenzuordnung kann zwischen Quellen schwanken; Zhang's eigene
# Tabelle 4 sollte massgeblich sein. A4B1C2D4 = Zhang-vorhergesagtes Optimum
# (SMD 40.52 um, Sektion 4.3 -> als zusaetzliches Verifikationscase vorne dran).
L16_ARRAY = [
    (1, 1, 1, 1), (1, 2, 2, 2), (1, 3, 3, 3), (1, 4, 4, 4),
    (2, 1, 2, 3), (2, 2, 1, 4), (2, 3, 4, 1), (2, 4, 3, 2),
    (3, 1, 3, 4), (3, 2, 4, 3), (3, 3, 1, 2), (3, 4, 2, 1),
    (4, 1, 4, 2), (4, 2, 3, 1), (4, 3, 2, 4), (4, 4, 1, 3),
]
EXTRAS = [
    (4, 1, 2, 4),   # Zhang-Optimum (SMD 40.52 um, separat verifizieren)
]


def build(a, b, c, d):
    """Flat user-settings dict fuer den headless Worker.

    Konvention (siehe tools/run_workflow.py _inject_into_schema): die
    JSON ist eine FLAT Map `field_name -> raw_value`, nicht das volle
    6-Tuple-Schema. Der Worker injiziert die Werte in slot[1] der
    Schema-Entries (rekursiv durch subdict-Selector-Branches).

    Wir setzen 6 Felder explizit; alle anderen kommen aus den
    Schema-Defaults in `../interface.json` (Zhang-Baseline). `Show details`
    auf `advanced` schalten, damit der Worker auch `enable ambient`,
    `end time` und `number of processors` aus dem advanced-Subdict
    propagiert.

    **Wichtig**: Zhang's DOE im Paper rechnet reinen Innen-Flow ohne
    Spray-Cone-Ambient-Domain -- Validation gegen Zhang's drei Metriken
    (Film, U_theta, p_inlet) braucht das nicht. `enable ambient = 0`
    haelt die Topologie v1 (uniformer 21-Block), kein Frustum-Knick,
    kleineres + stabileres Mesh, schnellerer Solver-Lauf. `end time =
    0.025` reicht fuer quasi-stationaeren Film + (annaehernd)
    konvergierten Vordruck.

    `_meta` ist eine reservierte, vom Worker ignorierte Sektion fuer
    menschlich lesbare Metadaten (Konvention auch in den A2-Examples).
    """
    code = "A%dB%dC%dD%d" % (a, b, c, d)
    return {
        "_meta": {
            "workflow": "A3_nozzle",
            "scenario": "Zhang L16 DOE case %s" % code,
            "note": "Generated by zhang_doe_configs/generate.py; DOE-code "
                    "wins over A/B/C/D top-level levels via parse_doe_code() "
                    "in the worker. ambient OFF (Zhang paper-conform: "
                    "inner flow only, no spray-cone domain).",
        },
        "project name": "A3_zhang_" + code,
        "DOE code (optional, e.g. A4B1C2D4)": code,
        "Show details": "advanced",
        "enable ambient (0/1)": "0",
        "end time [s]": "0.025",
        "number of processors": "128",
    }


def main():
    # schema is no longer read -- we emit a flat user-settings JSON. The
    # SCHEMA constant is kept for documentation purposes only.
    for (a, b, c, d) in L16_ARRAY + EXTRAS:
        code = "A%dB%dC%dD%d" % (a, b, c, d)
        cfg = build(a, b, c, d)
        path = HERE / ("%s.json" % code)
        with path.open("w", encoding="utf-8", newline="\n") as f:
            json.dump(cfg, f, indent=2)
        print("wrote %s" % path.name)
    print("%d configs written (%d L16 + %d extras)"
          % (len(L16_ARRAY) + len(EXTRAS), len(L16_ARRAY), len(EXTRAS)))


if __name__ == "__main__":
    main()
