#!/usr/bin/env python3
"""Parametric blockMesh generator for a 90° elbow with straight inlet/outlet.

Supports optional full-arc guide vanes at specified radii inside the bend.
The bend is split into N+1 radial sub-blocks; the inlet and outlet sub-divide
to match (so block faces are conformal). Vane interfaces remain INTERNAL in
blockMesh — use createBaffles (gen_createbaffles.py) to promote them to walls.

Quasi-2D: single cell in z with empty front/back patches.

Coordinate system:
    Inlet flows in +x direction from x=-L_in to x=0.
    Bend center at (0, R); bend curves from theta=0 (at x=0) to theta=90° (at y=R).
    Outlet flows in +y direction from y=R to y=R+L_out.
"""
from __future__ import annotations

import argparse
import math
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ElbowGeometry:
    H: float = 1.0
    W: float = 0.1
    R: float = 1.5
    L_in: float = 3.0
    L_out: float = 5.0
    nx_in: int = 60
    nx_bend: int = 80
    nx_out: int = 100
    ny: int = 40
    nz: int = 1
    scale: float = 1.0
    vane_radii: list[float] = field(default_factory=list)
    # Downstream-Verlängerung je Blech (in den Auslauf, Länge entlang +y ab y=R).
    # Parallel zu vane_radii (Nutzer-Reihenfolge); 0 = unmodifiziert (nur Bogen).
    # Leer => alle 0. Wird in gen_createbaffles per boxToFace bis y=R+ext genutzt.
    vane_ext: list[float] = field(default_factory=list)


def _vanes_sorted(g: "ElbowGeometry") -> list[tuple[float, float]]:
    """[(radius, ext), ...], nach Radius absteigend; ext defaultet auf 0."""
    exts = g.vane_ext if g.vane_ext else [0.0] * len(g.vane_radii)
    if len(exts) != len(g.vane_radii):
        raise ValueError(
            f"vane_ext (len {len(exts)}) must match vane_radii (len {len(g.vane_radii)})"
        )
    for e in exts:
        if not (0.0 <= e <= g.L_out):
            raise ValueError(f"vane_ext {e} must be in [0, L_out={g.L_out}]")
    return sorted(zip(g.vane_radii, exts), key=lambda p: p[0], reverse=True)


HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM                                        |
|  \\\\    /   O peration     | CFDPredict A2 - Leitblechkonfiguration          |
|   \\\\  /    A nd           | generated by gen_blockmesh.py                   |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def _radii(g: ElbowGeometry) -> list[float]:
    outer = g.R + g.H / 2
    inner = g.R - g.H / 2
    if inner <= 0:
        # R <= H/2 collapses the bend: the inner wall radius goes
        # non-positive and blockMesh dies with inward-pointing faces.
        # Guard here too (not only in the worker) so headless/Bayes
        # callers of ElbowGeometry get the clear error as well.
        raise ValueError(
            f"bend center radius R={g.R} must exceed H/2={g.H / 2}: "
            f"inner wall radius R-H/2={inner} is <= 0 (singular bend)"
        )
    pairs = _vanes_sorted(g)
    for r, _ in pairs:
        if not (inner < r < outer):
            raise ValueError(
                f"vane radius {r} must be strictly inside ({inner}, {outer})"
            )
    return [outer, *[r for r, _ in pairs], inner]


def _vid(c: int, r_idx: int, z_idx: int, n_radii: int) -> int:
    return c * n_radii * 2 + r_idx * 2 + z_idx


def _vertices(g: ElbowGeometry) -> list[tuple[float, float, float]]:
    R, W, Li, Lo = g.R, g.W, g.L_in, g.L_out
    rs = _radii(g)
    out: list[tuple[float, float, float]] = []
    for c in range(4):
        for r in rs:
            for z_idx in range(2):
                z = z_idx * W
                if c == 0:
                    out.append((-Li, R - r, z))
                elif c == 1:
                    out.append((0.0, R - r, z))
                elif c == 2:
                    out.append((r, R, z))
                else:
                    out.append((r, R + Lo, z))
    return out


def _blocks(g: ElbowGeometry):
    rs = _radii(g)
    n_radii = len(rs)
    n_bands = n_radii - 1
    ny_per_band = max(1, g.ny // n_bands)
    def vid(c, r, z): return _vid(c, r, z, n_radii)
    blocks = []
    for j in range(n_bands):
        for c, n_cells in [(0, g.nx_in), (1, g.nx_bend), (2, g.nx_out)]:
            verts = (
                vid(c,     j,   0), vid(c + 1, j,   0),
                vid(c + 1, j+1, 0), vid(c,     j+1, 0),
                vid(c,     j,   1), vid(c + 1, j,   1),
                vid(c + 1, j+1, 1), vid(c,     j+1, 1),
            )
            # band index j -> cellZone "band{j}" (vane interfaces are then the
            # faces between adjacent band zones; see gen_createbaffles.py)
            blocks.append((verts, (n_cells, ny_per_band, g.nz), j))
    return blocks


def _arc_edges(g: ElbowGeometry):
    rs = _radii(g)
    n_radii = len(rs)
    def vid(c, r, z): return _vid(c, r, z, n_radii)
    s = math.sin(math.pi / 4)
    edges = []
    for r_idx, r in enumerate(rs):
        for z_idx in range(2):
            z = z_idx * g.W
            mid = (r * s, g.R - r * s, z)
            edges.append(("arc", vid(1, r_idx, z_idx), vid(2, r_idx, z_idx), mid))
    return edges


def _patches(g: ElbowGeometry):
    rs = _radii(g)
    n_radii = len(rs)
    n_bands = n_radii - 1
    def vid(c, r, z): return _vid(c, r, z, n_radii)

    inlet, outlet, walls, front_back = [], [], [], []
    for j in range(n_bands):
        inlet.append((vid(0, j, 0), vid(0, j, 1), vid(0, j+1, 1), vid(0, j+1, 0)))
        outlet.append((vid(3, j, 0), vid(3, j+1, 0), vid(3, j+1, 1), vid(3, j, 1)))
        for c in (0, 1, 2):
            front_back.append((vid(c, j, 0), vid(c, j+1, 0),
                               vid(c+1, j+1, 0), vid(c+1, j, 0)))
            front_back.append((vid(c, j, 1), vid(c+1, j, 1),
                               vid(c+1, j+1, 1), vid(c, j+1, 1)))

    last = n_radii - 1
    for c in (0, 1, 2):
        walls.append((vid(c, 0, 0), vid(c+1, 0, 0),
                      vid(c+1, 0, 1), vid(c, 0, 1)))
        walls.append((vid(c, last, 0), vid(c, last, 1),
                      vid(c+1, last, 1), vid(c+1, last, 0)))

    if g.nz == 1:
        return [
            ("patch", "inlet",  inlet),
            ("patch", "outlet", outlet),
            ("wall",  "walls",  walls),
            ("empty", "frontAndBack", front_back),
        ]
    # 3D: merge front/back faces into the walls patch (no separate patch)
    return [
        ("patch", "inlet",  inlet),
        ("patch", "outlet", outlet),
        ("wall",  "walls",  walls + front_back),
    ]


def fmt_vec(v) -> str:
    return f"({v[0]:.6g} {v[1]:.6g} {v[2]:.6g})"


def render(g: ElbowGeometry) -> str:
    lines = [HEADER, f"convertToMeters {g.scale};", "", "vertices", "("]
    for i, v in enumerate(_vertices(g)):
        lines.append(f"    {fmt_vec(v)}  // {i}")
    lines += [");", "", "blocks", "("]
    for verts, cells, j in _blocks(g):
        vs = " ".join(str(x) for x in verts)
        cs = f"({cells[0]} {cells[1]} {cells[2]})"
        # cellZone name between vertex list and cell count
        lines.append(f"    hex ({vs}) band{j} {cs} simpleGrading (1 1 1)")
    lines += [");", "", "edges", "("]
    for kind, a, b, mid in _arc_edges(g):
        lines.append(f"    {kind} {a} {b} {fmt_vec(mid)}")
    lines += [");", "", "boundary", "("]
    for kind, name, faces in _patches(g):
        lines += [f"    {name}", "    {", f"        type {kind};",
                  "        faces", "        ("]
        for f in faces:
            lines.append(f"            ({f[0]} {f[1]} {f[2]} {f[3]})")
        lines += ["        );", "    }"]
    lines += [");", "", "mergePatchPairs", "(", ");", ""]
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=Path("blockMeshDict"))
    p.add_argument("--H", type=float, default=1.0)
    p.add_argument("--W", type=float, default=0.1)
    p.add_argument("--R", type=float, default=1.5)
    p.add_argument("--L-in", type=float, default=3.0, dest="L_in")
    p.add_argument("--L-out", type=float, default=5.0, dest="L_out")
    p.add_argument("--nx-in", type=int, default=60, dest="nx_in")
    p.add_argument("--nx-bend", type=int, default=80, dest="nx_bend")
    p.add_argument("--nx-out", type=int, default=100, dest="nx_out")
    p.add_argument("--ny", type=int, default=40)
    p.add_argument("--nz", type=int, default=1)
    p.add_argument("--scale", type=float, default=1.0)
    p.add_argument("--vane-radii", type=float, nargs="*", default=[],
                   dest="vane_radii",
                   help="absolute radii of guide vanes (strictly inside bend walls)")
    args = p.parse_args()

    g = ElbowGeometry(
        H=args.H, W=args.W, R=args.R,
        L_in=args.L_in, L_out=args.L_out,
        nx_in=args.nx_in, nx_bend=args.nx_bend, nx_out=args.nx_out,
        ny=args.ny, nz=args.nz, scale=args.scale,
        vane_radii=args.vane_radii,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    text = render(g)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(text.splitlines())} lines, {len(g.vane_radii)} vane(s))")


if __name__ == "__main__":
    main()
