#!/usr/bin/env python3
"""Generators for topoSetDict + createBafflesDict — promotes vane interfaces to walls.

**cellZone-basierte Identifizierung** (ab 2026-05-22, ersetzt cylinderAnnulusToFace):
gen_blockmesh weist jedem Radialband eine cellZone `band{j}` zu. Ein Blech an
Radius rs[i] ist dann genau das Interface **zwischen band{i-1} und band{i}** —
die Faces, die in beiden cellZones liegen. Das funktioniert im Bogen UND im
geraden Auslauf identisch und macht die Downstream-Verlängerung trivial.

    1. topoSet je Blech:
         (a) faceSet = cellToFace(band_lo) ∩ cellToFace(band_hi)  → volles Interface
             (Bogen + voller Auslauf; Einlauf hat x<0)
         (b) subset boxToFace: x ≥ 0 (Einlauf raus) und y ≤ R + L_ext_i
             → nur Bogen + Downstream-Verlängerung der Länge L_ext_i
         (c) setsToFaceZone (mit band_hi als Orientierungs-cellSet)
       L_ext_i = 0  → nur Bogen (reproduziert das alte Verhalten).

    2. createBaffles: faceZone → zwei koinzidente Wand-Patches
       (vaneN_master + vaneN_slave).
"""
from __future__ import annotations

import argparse
from pathlib import Path

from gen_blockmesh import ElbowGeometry, _vanes_sorted, HEADER as _BM_HEADER


def _header(obj: str, generator: str) -> str:
    return (
        _BM_HEADER
        .replace("object      blockMeshDict;", f"object      {obj};")
        .replace("generated by gen_blockmesh.py", f"generated by {generator}")
    )


def render_toposet(g: ElbowGeometry) -> str:
    if not g.vane_radii:
        raise ValueError("no vanes (vane_radii is empty)")
    R, H, W = g.R, g.H, g.W
    eps = 1e-3
    pairs = _vanes_sorted(g)          # [(radius, ext), ...] absteigend
    # Box-Grenzen: x>=0 schließt den Einlauf (x<0) aus; y<=R+ext begrenzt die
    # Downstream-Verlängerung. x/y/z weit genug für Bogen + Auslauf.
    x_lo, x_hi = 0.0, R + H / 2 + eps
    y_lo = -H / 2 - eps
    z_lo, z_hi = -eps, W + eps

    lines = [_header("topoSetDict", "gen_createbaffles.py"), "", "actions", "("]
    for i, (r, ext) in enumerate(pairs, start=1):
        lo, hi = i - 1, i            # Blech i = Interface band{i-1} | band{i}
        y_hi = R + ext + eps         # ext=0 -> nur Bogen (y<=R)
        lines += [
            "    {",
            f"        name    v{i}lo;",
            "        type    cellSet;",
            "        action  new;",
            "        source  zoneToCell;",
            f"        zones   (band{lo});",
            "    }",
            "    {",
            f"        name    v{i}hi;",
            "        type    cellSet;",
            "        action  new;",
            "        source  zoneToCell;",
            f"        zones   (band{hi});",
            "    }",
            "    {",
            f"        name    vane{i}Faces;",
            "        type    faceSet;",
            "        action  new;",
            "        source  cellToFace;",
            f"        sets    (v{i}lo);",
            "        option  all;",
            "    }",
            "    {",
            f"        name    vane{i}Faces;",
            "        type    faceSet;",
            "        action  subset;",
            "        source  cellToFace;",
            f"        sets    (v{i}hi);",
            "        option  all;",
            "    }",
            "    {",
            f"        name    vane{i}Faces;",
            "        type    faceSet;",
            "        action  subset;",
            "        source  boxToFace;",
            f"        box     ({x_lo:.6g} {y_lo:.6g} {z_lo:.6g}) "
            f"({x_hi:.6g} {y_hi:.6g} {z_hi:.6g});",
            "    }",
            "    {",
            f"        name    vane{i}FaceZone;",
            "        type    faceZoneSet;",
            "        action  new;",
            "        source  setsToFaceZone;",
            f"        faceSet vane{i}Faces;",
            f"        cellSet v{i}hi;",
            "    }",
        ]
    lines += [");", ""]
    return "\n".join(lines)


def render(g: ElbowGeometry) -> str:
    if not g.vane_radii:
        raise ValueError("no vanes (vane_radii is empty)")
    n = len(g.vane_radii)
    lines = [
        _header("createBafflesDict", "gen_createbaffles.py"),
        "",
        "internalFacesOnly true;",
        "fields            false;",
        "",
        "baffles",
        "{",
    ]
    for i in range(1, n + 1):
        lines += [
            f"    vane{i}",
             "    {",
             "        type            faceZone;",
            f"        zoneName        vane{i}FaceZone;",
             "        patches",
             "        {",
            f"            master {{ name vane{i}_master; type wall; }}",
            f"            slave  {{ name vane{i}_slave;  type wall; }}",
             "        }",
             "    }",
        ]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--target-dir", type=Path, default=Path("system"))
    p.add_argument("--R", type=float, default=1.5)
    p.add_argument("--H", type=float, default=1.0)
    p.add_argument("--W", type=float, default=0.1)
    p.add_argument("--vane-radii", type=float, nargs="+", required=True,
                   dest="vane_radii")
    args = p.parse_args()
    g = ElbowGeometry(R=args.R, H=args.H, W=args.W, vane_radii=args.vane_radii)
    args.target_dir.mkdir(parents=True, exist_ok=True)
    (args.target_dir / "topoSetDict").write_text(render_toposet(g),
                                                  encoding="utf-8", newline="\n")
    (args.target_dir / "createBafflesDict").write_text(render(g),
                                                        encoding="utf-8", newline="\n")
    print(f"wrote topoSetDict + createBafflesDict to {args.target_dir} "
          f"({len(g.vane_radii)} vane(s))")


if __name__ == "__main__":
    main()
